### PR TITLE
Added detekt task with type resolution

### LINKED ISSUE #41: Enable type resolution in Detekt
[Type Resolution](https://detekt.github.io/detekt/type-resolution.html) is a feature in detekt enabling more powerful inspections. We need to investigate is it possible to enable this feature for `detektAll`.

### PR DESCRIPTION
**Pull request by rwqwr**
Closes https://github.com/RedMadRobot/gradle-infrastructure/issues/41

### CODE REVIEW

**Comment by osipxd** [comment]
@rwqwr, you can disable

**Comment by osipxd** [comment]
@rwqwr, you can disable `ArgumentListWrapping` until it fixed
```yaml
ArgumentListWrapping:
    # TODO: Enable after update to ktlint 0.42+
    #  Issue: https://github.com/pinterest/ktlint/issues/1159
    active: false
```

**Comment by rwqwr** [comment]
Another problem, the samples contain irrelevant versions of the dependencies, but this is not important for them. How do you feel about disabling the rule in samples that checks dependency versions via lintOptions?
```kotlin
lintOptions {
    disable("GradleDependency")
}
```

I can create a new PR by disabling inappropriate rules like ArgumentListWrapping and GradleDependency.

**Comment by osipxd** [comment]
> Another problem, the samples contain irrelevant versions of the dependencies, but this is not important for them. 

I think it's better to keep dependencies in samples up to date, otherwise samples may become unusable at some moment.

**Comment by rwqwr** [comment]
Yes you are right! I mean we can do this independently of the working commits, we can update the dependencies in a separate PR. Now every PR can be interrupted by checking the GradleVersion rule, but the PR doesn't change any dependency.

**Review by osipxd — APPROVED** [review]

**Pull request merged**
